### ISSUE TITLE
Provide "Getting Started" in README

### ISSUE THREAD

**Issue by stordahl** [sanity-io/sanity-studio-secrets#2]
Although this isn't really ready for prod, I'm going to be integrating it in [sanity-plugin-snipcart-orders](https://github.com/stordahl/sanity-plugin-snipcart-orders) and would love to see a thorough "getting started" section in the README. Once I've successfully integrated it, I'll submit a PR to close this issue.

**Comment by runeb** [comment]
Please open a PR if you have additions. Closing this issue.
