### ISSUE TITLE
Secrets are exposed through `sanity dataset export`

### ISSUE THREAD

**Issue by janhoogeveen** [sanity-io/sanity-studio-secrets#3]
I'm looking into making a daily backup of our public Sanity dataset and publish it on a public GitHub repository.
When I'm using `sanity dataset export production` I see that both `drafts` and `secrets` are exported.

When I try to run `sanity dataset export production --no-drafts` I would expect all documents prefixed with a `.` to be hidden from the export. However, that's not the case. Drafts are hidden, but secrets are still exported.

Is there a way to get all documents from a public dataset without exposing secrets?

**Comment by runeb** [comment]
Yes, the secrets are stored on a normal document, only that it is not publicly accessible in public datasets. It will be exported along with all other documents however, so take care to prune your exports if you need to publish them.
