### ISSUE TITLE
Please bump version to include latest fix for API deprecation 

### ISSUE THREAD

**Issue by dorelljames** [sanity-io/sanity-studio-secrets#4]
![image](https://user-images.githubusercontent.com/977413/118470483-4dba3580-b739-11eb-8ff3-ce867015b4f9.png)

Can you please release a new version at NPM to get those above fixed? I tried the latest one locally and it fixed the error.

**Comment by dorelljames** [comment]
@runeb can you please take a look at this? thanks

**Comment by runeb** [comment]
@dorelljames 0.0.5 released to include this
